# Composite Action für FinOps Analysis
name: 'FinOps Analysis and Report'
description: 'Führt Azure FinOps Analyse durch und generiert einen Report'

inputs:
  config-path:
    description: 'Pfad zur finops.config.json Datei (relativ zum Submodul-Root)'
    required: true
  azure-client-id:
    description: 'Azure Client ID für Authentication'
    required: true
  azure-tenant-id:
    description: 'Azure Tenant ID für Authentication'
    required: true
  azure-subscription-id:
    description: 'Azure Subscription ID'
    required: true

outputs:
  report-path:
    description: 'Pfad zum generierten FinOps Report'
    value: ${{ steps.upload-report.outputs.artifact-id }}

runs:
  using: 'composite'
  steps:
    # ====================================================================
    # CONFIGURATION
    # ====================================================================
    - name: 'Read configuration from file'
      id: config
      shell: bash
      run: |
        # Pfad relativ zum Action-Verzeichnis
        CONFIG_FILE="${{ github.action_path }}/${{ inputs.config-path }}"

        # Prüfe, ob die Config-Datei existiert
        if [[ ! -f "$CONFIG_FILE" ]]; then
          echo "::error::Configuration file not found: $CONFIG_FILE"
          exit 1
        fi

        # Validiere JSON
        if ! jq -e . "$CONFIG_FILE" > /dev/null; then
          echo "::error::Invalid JSON in configuration file: $CONFIG_FILE"
          exit 1
        fi

        echo "INFO: Configuration loaded from $CONFIG_FILE"

        # Speichere absoluten Pfad für spätere Steps
        echo "config_file=$CONFIG_FILE" >> "$GITHUB_OUTPUT"

        # Lese Module-Status
        disks_enabled=$(jq -r '.analysis_modules.unattached_disks.enabled' "$CONFIG_FILE")
        echo "unattached_disks_enabled=$disks_enabled" >> "$GITHUB_OUTPUT"

        ips_enabled=$(jq -r '.analysis_modules.unassociated_public_ips.enabled' "$CONFIG_FILE")
        echo "unassociated_public_ips_enabled=$ips_enabled" >> "$GITHUB_OUTPUT"

        snapshots_enabled=$(jq -r '.analysis_modules.old_snapshots.enabled' "$CONFIG_FILE")
        echo "old_snapshots_enabled=$snapshots_enabled" >> "$GITHUB_OUTPUT"

        advisor_enabled=$(jq -r '.analysis_modules.azure_advisor.enabled' "$CONFIG_FILE")
        echo "azure_advisor_enabled=$advisor_enabled" >> "$GITHUB_OUTPUT"

        vms_enabled=$(jq -r '.analysis_modules.underutilized_vms.enabled' "$CONFIG_FILE")
        echo "underutilized_vms_enabled=$vms_enabled" >> "$GITHUB_OUTPUT"

        echo "--- Enabled Modules ---"
        echo "Unattached Disks: $disks_enabled"
        echo "Unassociated IPs: $ips_enabled"
        echo "Old Snapshots: $snapshots_enabled"
        echo "Azure Advisor: $advisor_enabled"
        echo "Underutilized VMs: $vms_enabled"
        echo "----------------------"

    # ====================================================================
    # AZURE AUTHENTICATION
    # ====================================================================
    - name: 'Azure Login'
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.azure-client-id }}
        tenant-id: ${{ inputs.azure-tenant-id }}
        subscription-id: ${{ inputs.azure-subscription-id }}

    # ====================================================================
    # ANALYSIS MODULES
    # ====================================================================
    - name: 'Module: Find unattached disks'
      if: steps.config.outputs.unattached_disks_enabled == 'true'
      shell: bash
      run: |
        true > analysis-unattached-disks.tsv

        mapfile -t RGS_TO_SCAN < <(comm -23 \
            <(az group list --query "[].name" -o tsv | sort) \
            <(jq -r '.global_settings.excluded_resource_groups[]' "${{ steps.config.outputs.config_file }}" | sort) \
        )

        echo "INFO: Found ${#RGS_TO_SCAN[@]} resource groups to scan."

        for rg in "${RGS_TO_SCAN[@]}"; do
          echo "   - Checking for unattached disks in resource group: $rg"
          az disk list --resource-group "$rg" --query "[?diskState=='Unattached'].{Name:name, ResourceGroup:resourceGroup, SizeGB:diskSizeGb, Location:location}" --output tsv >> analysis-unattached-disks.tsv || true
        done

        RESULT_COUNT=$(wc -l < analysis-unattached-disks.tsv)
        echo "Found $RESULT_COUNT unattached disks."

    - name: 'Module: Find unassociated public IPs'
      if: steps.config.outputs.unassociated_public_ips_enabled == 'true'
      shell: bash
      run: |
        EXCLUSION_FILTER=""
        for rg in $(jq -r '.global_settings.excluded_resource_groups[]' "${{ steps.config.outputs.config_file }}"); do
          EXCLUSION_FILTER+="&& resourceGroup!='$rg'"
        done

        az network public-ip list --query "[?ipConfiguration==null $EXCLUSION_FILTER].{Name:name, ResourceGroup:resourceGroup, IPAddress:ipAddress, Location:location}" --output tsv > analysis-unassociated-public-ips.tsv || true
        echo "Found $(wc -l < analysis-unassociated-public-ips.tsv) unassociated public IPs."

    - name: 'Module: Find old snapshots'
      if: steps.config.outputs.old_snapshots_enabled == 'true'
      shell: bash
      run: |
        RETENTION_DAYS=$(jq -r '.analysis_modules.old_snapshots.retention_days' "${{ steps.config.outputs.config_file }}")
        cutoff_date=$(date -d "-$RETENTION_DAYS days" -u +'%Y-%m-%dT%H:%M:%SZ')

        EXCLUSION_FILTER=""
        for rg in $(jq -r '.global_settings.excluded_resource_groups[]' "${{ steps.config.outputs.config_file }}"); do
          EXCLUSION_FILTER+="&& resourceGroup!='$rg'"
        done

        az snapshot list --query "[?timeCreated < '$cutoff_date' $EXCLUSION_FILTER].{Name:name, ResourceGroup:resourceGroup, SizeGB:diskSizeGb, Location:location}" --output tsv > analysis-old-snapshots.tsv || true
        echo "Found $(wc -l < analysis-old-snapshots.tsv) snapshots older than $RETENTION_DAYS days."

    - name: 'Module: Get Azure Advisor recommendations'
      if: steps.config.outputs.azure_advisor_enabled == 'true'
      shell: bash
      run: |
        CATEGORIES=$(jq -r '.analysis_modules.azure_advisor.categories | join(" ")' "${{ steps.config.outputs.config_file }}")

        az advisor recommendation list --category "$CATEGORIES" --query "[].{Description:shortDescription.problem, Resource:resourceMetadata.resourceId, Category:category}" --output tsv > analysis-azure-advisor-recommendations.tsv || true
        echo "Found $(wc -l < analysis-azure-advisor-recommendations.tsv) Advisor recommendations for categories: \"$CATEGORIES\"."

    - name: 'Module: Find underutilized VMs'
      if: steps.config.outputs.underutilized_vms_enabled == 'true'
      shell: bash
      env:
        AZURE_SUBSCRIPTION_ID: ${{ inputs.azure-subscription-id }}
      run: |
        echo "--- Running Python script for Underutilized VM analysis ---"

        python -m pip install --upgrade pip --quiet
        pip install --quiet --no-warn-script-location \
          azure-identity \
          azure-mgmt-resource \
          azure-mgmt-compute \
          azure-mgmt-monitor

        echo "INFO: Python dependencies installed."

        # Kopiere die Config für das Python-Skript ins aktuelle Verzeichnis
        cp "${{ steps.config.outputs.config_file }}" runtime_config.json

        # Führe das Python-Skript aus dem Submodul aus
        python "${{ github.action_path }}/../../.github/scripts/find_underutilized_vms.py"

        echo "--- Python script finished ---"

    # ====================================================================
    # ARTIFACT UPLOAD (Analysis Results)
    # ====================================================================
    - name: 'Upload analysis results as artifact'
      uses: actions/upload-artifact@v4
      with:
        name: finops-analysis-results
        path: analysis-*.tsv
        if-no-files-found: ignore

    # ====================================================================
    # AZURE LOGOUT
    # ====================================================================
    - name: 'Azure Logout'
      shell: bash
      run: |
        az logout
        az cache purge
        az account clear

    # ====================================================================
    # REPORT GENERATION
    # ====================================================================
    - name: 'Generate Markdown Report'
      shell: bash
      run: |
        SCRIPT_PATH="${{ github.action_path }}/../../.github/scripts/generate-report.sh"
        chmod +x "$SCRIPT_PATH"
        "$SCRIPT_PATH"

    - name: 'Upload final report'
      id: upload-report
      uses: actions/upload-artifact@v4
      with:
        name: finops-cost-report
        path: report.md
        if-no-files-found: error
